[package]
name = "faisync"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.23.0"
